# Generated by Django 5.2.6 on 2025-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('code', models.CharField()),
                ('comment', models.CharField()),
                ('saved_at', models.DateField()),
            ],
        ),
    ]
