# Generated by Django 5.2.6 on 2025-10-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='콤마로 구분된 카테고리 코드', max_length=500, verbose_name='카테고리'),
        ),
    ]
